<a href="https://colab.research.google.com/github/morcellinus/Introduction_to_Deep_Learning/blob/main/LJM_lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2 – Tensors

In [ ]:
import torch

## Create empty tensors
- Uninitialised tensors

In [ ]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)

torch.ones(3, 1, 2)

tensor([-2.0073e+35])

1-D tensor
tensor([-2.0073e+35,  3.0701e-41])

2-D tensor
tensor([[-2.0073e+35,  3.0701e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

3-D tensor
 tensor([[[-2.0074e+35],
         [ 3.0701e-41],
         [ 5.0447e-44]],

        [[ 0.0000e+00],
         [        nan],
         [ 0.0000e+00]]])


tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

## Initialise tensors to scalar, random values, zeros or ones

In [ ]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.1379, 0.9361, 0.3738],
        [0.0576, 0.0855, 0.0272]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
# Reshaping (2D -> 1D)

x = torch.rand(4, 4)
x.shape
y = x.reshape(16)
y

tensor([0.0713, 0.7231, 0.8564, 0.7892, 0.3272, 0.9396, 0.5878, 0.2571, 0.4426,
        0.4835, 0.6240, 0.9058, 0.2047, 0.6718, 0.3240, 0.4706])

## Construct tensor from data

In [ ]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [ ]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[ 5.2548, 11.2986, 15.9907],
        [11.2532, 16.4977, 12.8811]])
tensor([[ 5, 11, 15],
        [11, 16, 12]], dtype=torch.int32)


### Create a separate copy



In [ ]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.4402, 0.6822],
        [0.7523, 0.9359]])

y = 
tensor([[0.5542, 0.3835],
        [0.5229, 0.8536]])

x + y = 
tensor([[0.9943, 1.0657],
        [1.2752, 1.7896]])
x - y = 
tensor([[-0.1140,  0.2987],
        [ 0.2293,  0.0823]])
x * y = 
tensor([[0.2439, 0.2616],
        [0.3934, 0.7989]])
x / y = 
tensor([[0.7943, 1.7788],
        [1.4386, 1.0964]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.0448, 0.5080],
        [0.5344, 0.8500]])

y = 
tensor([[0.3264, 0.0341],
        [0.1144, 0.3492]])

y + x = tensor([[0.3712, 0.5421],
        [0.6488, 1.1992]])
y - x = tensor([[0.3264, 0.0341],
        [0.1144, 0.3492]])
y * x = tensor([[0.0146, 0.0173],
        [0.0611, 0.2968]])
y / x = tensor([[0.3264, 0.0341],
        [0.1144, 0.3492]])


## Accessing tensors

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

tensor([[0.8335, 0.9758, 0.2251],
        [0.2424, 0.9790, 0.7908],
        [0.0199, 0.3416, 0.3340],
        [0.3808, 0.7337, 0.5929],
        [0.4990, 0.1046, 0.3517]])
tensor([0.8335, 0.2424, 0.0199, 0.3808, 0.4990])
tensor([0.2424, 0.9790, 0.7908])
tensor(0.3340)
0.9790407419204712
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [ ]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.5982, 0.9619, 0.8296],
        [0.5381, 0.1905, 0.1481],
        [0.0809, 0.2593, 0.3537],
        [0.3014, 0.6264, 0.6077],
        [0.6249, 0.5922, 0.7574]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements and each of these have 4 elements. This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [ ]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [ ]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(1, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

Original:
tensor([[0.8557, 0.9721, 0.7973, 0.6047],
        [0.4604, 0.0560, 0.1960, 0.2153],
        [0.1093, 0.8829, 0.0015, 0.6302],
        [0.2895, 0.0272, 0.6683, 0.2886]])
torch.Size([4, 4])
Reshaped to 1-D:
tensor([0.8557, 0.9721, 0.7973, 0.6047, 0.4604, 0.0560, 0.1960, 0.2153, 0.1093,
        0.8829, 0.0015, 0.6302, 0.2895, 0.0272, 0.6683, 0.2886])
Reshaped to 2-D:
tensor([[0.8557, 0.9721],
        [0.7973, 0.6047],
        [0.4604, 0.0560],
        [0.1960, 0.2153],
        [0.1093, 0.8829],
        [0.0015, 0.6302],
        [0.2895, 0.0272],
        [0.6683, 0.2886]])
Reshaped to 2 x Unspecified 2-D:
tensor([[0.8557, 0.9721, 0.7973, 0.6047, 0.4604, 0.0560, 0.1960, 0.2153, 0.1093,
         0.8829, 0.0015, 0.6302, 0.2895, 0.0272, 0.6683, 0.2886]])
torch.Size([1, 16])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])


## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [ ]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Exercise

In [ ]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )

# Print x

x = torch.linspace(0, 2, steps = 100)
print(x)



tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [ ]:
# 3. Print the first 5 numbers in x.

print(x[0:5])

# 4. Print the last 5 numbers in x

print(x[-5:])


tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808])
tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [ ]:
# 5. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )

# Print y

y = torch.rand(100)
print(y)

tensor([0.6543, 0.2630, 0.0084, 0.4652, 0.1890, 0.2093, 0.7437, 0.1015, 0.7925,
        0.4059, 0.6678, 0.4531, 0.3742, 0.0641, 0.2635, 0.4953, 0.8234, 0.8391,
        0.1554, 0.0811, 0.7230, 0.4292, 0.3627, 0.0472, 0.9530, 0.1059, 0.2833,
        0.9701, 0.0097, 0.4086, 0.4652, 0.7776, 0.8681, 0.3996, 0.7943, 0.5026,
        0.8457, 0.9873, 0.8360, 0.4756, 0.5858, 0.8075, 0.2410, 0.6159, 0.5274,
        0.1898, 0.0321, 0.3687, 0.7209, 0.5870, 0.3124, 0.0078, 0.8645, 0.6573,
        0.9862, 0.4957, 0.7316, 0.6962, 0.0526, 0.8371, 0.0601, 0.9799, 0.7515,
        0.7743, 0.8969, 0.7842, 0.2248, 0.7770, 0.1613, 0.0259, 0.3677, 0.0898,
        0.2584, 0.5259, 0.2429, 0.8259, 0.3638, 0.0164, 0.4720, 0.5113, 0.0045,
        0.5991, 0.2447, 0.8324, 0.8418, 0.3512, 0.7698, 0.0521, 0.1514, 0.8823,
        0.7005, 0.8508, 0.6717, 0.2128, 0.7711, 0.9720, 0.7428, 0.8844, 0.6222,
        0.7454])


In [ ]:
# 6. Multiply x and y, store the result in z


# Print z


z = torch.mul(x,y)
print(z)
z.shape

tensor([0.0000e+00, 5.3133e-03, 3.3752e-04, 2.8194e-02, 1.5269e-02, 2.1145e-02,
        9.0149e-02, 1.4347e-02, 1.2808e-01, 7.3798e-02, 1.3490e-01, 1.0069e-01,
        9.0724e-02, 1.6836e-02, 7.4520e-02, 1.5011e-01, 2.6614e-01, 2.8817e-01,
        5.6510e-02, 3.1128e-02, 2.9212e-01, 1.8210e-01, 1.6119e-01, 2.1935e-02,
        4.6208e-01, 5.3471e-02, 1.4880e-01, 5.2917e-01, 5.5018e-03, 2.3936e-01,
        2.8193e-01, 4.8699e-01, 5.6119e-01, 2.6642e-01, 5.4557e-01, 3.5538e-01,
        6.1507e-01, 7.3797e-01, 6.4178e-01, 3.7470e-01, 4.7340e-01, 6.6884e-01,
        2.0448e-01, 5.3501e-01, 4.6881e-01, 1.7251e-01, 2.9818e-02, 3.5010e-01,
        6.9909e-01, 5.8112e-01, 3.1559e-01, 8.0636e-03, 9.0820e-01, 7.0376e-01,
        1.0759e+00, 5.5074e-01, 8.2764e-01, 8.0171e-01, 6.1682e-02, 9.9774e-01,
        7.2903e-02, 1.2075e+00, 9.4129e-01, 9.8549e-01, 1.1597e+00, 1.0298e+00,
        2.9970e-01, 1.0518e+00, 2.2152e-01, 3.6166e-02, 5.2001e-01, 1.2877e-01,
        3.7579e-01, 7.7562e-01, 3.6309e-

torch.Size([100])

In [ ]:
# 7. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2

# Print z2
z2 = z.reshape(5, 20)
print(z2)

tensor([[0.0000e+00, 5.3133e-03, 3.3752e-04, 2.8194e-02, 1.5269e-02, 2.1145e-02,
         9.0149e-02, 1.4347e-02, 1.2808e-01, 7.3798e-02, 1.3490e-01, 1.0069e-01,
         9.0724e-02, 1.6836e-02, 7.4520e-02, 1.5011e-01, 2.6614e-01, 2.8817e-01,
         5.6510e-02, 3.1128e-02],
        [2.9212e-01, 1.8210e-01, 1.6119e-01, 2.1935e-02, 4.6208e-01, 5.3471e-02,
         1.4880e-01, 5.2917e-01, 5.5018e-03, 2.3936e-01, 2.8193e-01, 4.8699e-01,
         5.6119e-01, 2.6642e-01, 5.4557e-01, 3.5538e-01, 6.1507e-01, 7.3797e-01,
         6.4178e-01, 3.7470e-01],
        [4.7340e-01, 6.6884e-01, 2.0448e-01, 5.3501e-01, 4.6881e-01, 1.7251e-01,
         2.9818e-02, 3.5010e-01, 6.9909e-01, 5.8112e-01, 3.1559e-01, 8.0636e-03,
         9.0820e-01, 7.0376e-01, 1.0759e+00, 5.5074e-01, 8.2764e-01, 8.0171e-01,
         6.1682e-02, 9.9774e-01],
        [7.2903e-02, 1.2075e+00, 9.4129e-01, 9.8549e-01, 1.1597e+00, 1.0298e+00,
         2.9970e-01, 1.0518e+00, 2.2152e-01, 3.6166e-02, 5.2001e-01, 1.2877e-01,
       

In [ ]:
# 8. Get the sum of each row in z2

print(torch.sum(z2, dim = 1))

# 9. Get the mean of each column in z3

print(torch.mean(z2, dim = 0))

tensor([ 1.5864,  6.9627, 10.4342, 12.5642, 21.8165])
tensor([0.1691, 0.6088, 0.3425, 0.5933, 0.7069, 0.3760, 0.3812, 0.4074, 0.2647,
        0.5034, 0.5052, 0.4577, 0.6368, 0.4325, 0.7047, 0.8346, 0.7416, 0.7173,
        0.5471, 0.7421])


In [ ]:
# 10. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3

# Print z3

z3 = z.reshape(5, 4, -1)
print(z3)

tensor([[[0.0000e+00, 5.3133e-03, 3.3752e-04, 2.8194e-02, 1.5269e-02],
         [2.1145e-02, 9.0149e-02, 1.4347e-02, 1.2808e-01, 7.3798e-02],
         [1.3490e-01, 1.0069e-01, 9.0724e-02, 1.6836e-02, 7.4520e-02],
         [1.5011e-01, 2.6614e-01, 2.8817e-01, 5.6510e-02, 3.1128e-02]],

        [[2.9212e-01, 1.8210e-01, 1.6119e-01, 2.1935e-02, 4.6208e-01],
         [5.3471e-02, 1.4880e-01, 5.2917e-01, 5.5018e-03, 2.3936e-01],
         [2.8193e-01, 4.8699e-01, 5.6119e-01, 2.6642e-01, 5.4557e-01],
         [3.5538e-01, 6.1507e-01, 7.3797e-01, 6.4178e-01, 3.7470e-01]],

        [[4.7340e-01, 6.6884e-01, 2.0448e-01, 5.3501e-01, 4.6881e-01],
         [1.7251e-01, 2.9818e-02, 3.5010e-01, 6.9909e-01, 5.8112e-01],
         [3.1559e-01, 8.0636e-03, 9.0820e-01, 7.0376e-01, 1.0759e+00],
         [5.5074e-01, 8.2764e-01, 8.0171e-01, 6.1682e-02, 9.9774e-01]],

        [[7.2903e-02, 1.2075e+00, 9.4129e-01, 9.8549e-01, 1.1597e+00],
         [1.0298e+00, 2.9970e-01, 1.0518e+00, 2.2152e-01, 3.6166e-02],
